"use client";

import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      {/* Navigation */}
      <nav className="border-b border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="flex items-center gap-2">
              <div className="w-8 h-8 bg-gradient-to-br from-primary to-blue-500 rounded-md flex items-center justify-center shadow-sm">
                <span className="text-white font-semibold text-lg">I</span>
              </div>
              <span className="text-h4 font-display font-semibold text-gray-900 dark:text-gray-50">
                IoTDB Enhanced
              </span>
            </Link>
            <div className="hidden md:flex items-center gap-8">
              <Link href="/" className="text-body text-gray-600 dark:text-gray-400 hover:text-primary transition-colors">
                Home
              </Link>
              <a href="/pricing" className="text-body text-gray-600 dark:text-gray-400 hover:text-primary transition-colors">
                Pricing
              </a>
              <Link href="/dashboard">
                <Button variant="primary" size="sm">
                  Sign In
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-20 pb-16 px-4 sm:px-6 lg:px-8 bg-pattern-dots">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 border border-primary/20 px-4 py-1.5 text-sm font-medium text-primary mb-6">
            About Us
          </div>
          <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-semibold text-gray-900 dark:text-gray-50 mb-6 tracking-tight">
            Building the Future of
            <br />
            <span className="text-primary">Time Series Analytics</span>
          </h1>
          <p className="text-body-lg text-gray-600 dark:text-gray-400 leading-relaxed max-w-2xl mx-auto">
            We are dedicated to providing the most powerful time series data analytics platform
            for the industrial IoT domain, empowering teams to make data-driven decisions at scale.
          </p>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {[
              { number: "2024", label: "Founded", icon: "📅" },
              { number: "500+", label: "Enterprise Users", icon: "🏢" },
              { number: "50+", label: "Countries", icon: "🌍" },
              { number: "1B+", label: "Data Points/Day", icon: "📊" },
            ].map((stat, idx) => (
              <div
                key={idx}
                className="stagger-slide-up bg-white dark:bg-gray-800 rounded-xl p-6 text-center relative overflow-hidden group transition-all duration-200"
                style={{ animationDelay: `${idx * 80}ms`, boxShadow: "rgba(0, 0, 0, 0.08) 0px 0px 0px 1px, rgba(0, 0, 0, 0.04) 0px 2px 2px, #fafafa 0px 0px 0px 1px" }}
              >
                {/* Subtle gradient top border */}
                <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-primary to-blue-400" />
                <div className="text-2xl mb-3">{stat.icon}</div>
                <div className="text-3xl md:text-4xl font-display font-semibold text-primary mb-2">
                  {stat.number}
                </div>
                <div className="text-body-sm text-gray-500 dark:text-gray-400 font-medium">
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Mission Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-h1 font-display text-gray-900 dark:text-gray-50 mb-6">
                Our Mission
              </h2>
              <p className="text-body text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                IoTDB Enhanced is dedicated to making time series data analytics simple, powerful,
                and accessible. We believe that every piece of data generated by industrial devices
                contains immense value — our mission is to help you discover and leverage that value.
              </p>
              <p className="text-body text-gray-600 dark:text-gray-400 leading-relaxed">
                By integrating cutting-edge AI technology, we provide not only data storage and query
                capabilities, but also prediction, early warning, and intelligent analysis features —
                helping enterprises identify and solve problems before they occur.
              </p>
            </div>
            <div className="bg-mesh-gradient rounded-xl p-8"
                 style={{ boxShadow: "rgba(0, 0, 0, 0.08) 0px 0px 0px 1px, rgba(0, 0, 0, 0.04) 0px 2px 2px, #fafafa 0px 0px 0px 1px" }}>
              <div className="grid grid-cols-2 gap-8">
                {[
                  { value: "99.99%", label: "Platform Uptime" },
                  { value: "<1ms", label: "Query Latency" },
                  { value: "10M+", label: "Points per Second" },
                  { value: "24/7", label: "Expert Support" },
                ].map((stat, idx) => (
                  <div key={idx} className="text-center">
                    <div className="text-2xl font-display font-semibold text-primary mb-1">
                      {stat.value}
                    </div>
                    <div className="text-body-sm text-gray-500 dark:text-gray-400">
                      {stat.label}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Values Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-h1 font-display text-gray-900 dark:text-gray-50 mb-4">
              Core Values
            </h2>
            <p className="text-body-lg text-gray-600 dark:text-gray-400">
              The principles that guide everything we build
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                number: "01",
                title: "Security First",
                description: "Data security is our top priority. We employ enterprise-grade encryption, access control, and audit mechanisms to keep your data safe at all times.",
                color: "from-primary to-blue-400",
                iconPath: "M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z",
              },
              {
                number: "02",
                title: "Pursuit of Excellence",
                description: "We continuously optimize performance, improve user experience, and introduce the latest technologies to keep our platform at the industry's leading edge.",
                color: "from-emerald-500 to-teal-400",
                iconPath: "M13 10V3L4 14h7v7l9-11h-7z",
              },
              {
                number: "03",
                title: "Customer First",
                description: "We listen to our users, respond quickly to needs, and continuously improve our product to ensure every user gets the best possible experience.",
                color: "from-blue-500 to-cyan-400",
                iconPath: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z",
              },
            ].map((value, idx) => (
              <div
                key={idx}
                className="stagger-slide-up relative bg-white dark:bg-gray-800 rounded-xl p-8 group hover:shadow-[rgba(0,0,0,0.08)_0px_0px_0px_1px,rgba(0,0,0,0.06)_0px_4px_4px,rgba(0,0,0,0.04)_0px_8px_8px_-8px,#fafafa_0px_0px_0px_1px] transition-all duration-300"
                style={{ animationDelay: `${idx * 80}ms`, boxShadow: "rgba(0, 0, 0, 0.08) 0px 0px 0px 1px, rgba(0, 0, 0, 0.04) 0px 2px 2px, #fafafa 0px 0px 0px 1px" }}
              >
                {/* Faded number background */}
                <div className="absolute top-4 right-4 text-7xl font-display font-semibold text-gray-100 dark:text-gray-700/50 select-none leading-none">
                  {value.number}
                </div>

                <div className="relative z-10">
                  <div className={`w-12 h-12 rounded-lg bg-gradient-to-br ${value.color} flex items-center justify-center mb-4 shadow-sm transition-transform duration-200 group-hover:scale-110`}>
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={value.iconPath} />
                    </svg>
                  </div>
                  <h3 className="text-h4 font-display font-semibold text-gray-900 dark:text-gray-50 mb-3">
                    {value.title}
                  </h3>
                  <p className="text-body text-gray-600 dark:text-gray-400 leading-relaxed">
                    {value.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Team Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-h1 font-display text-gray-900 dark:text-gray-50 mb-4">
              Leadership Team
            </h2>
            <p className="text-body-lg text-gray-600 dark:text-gray-400">
              Seasoned experts from world-class technology companies
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                name: "Ming Zhang",
                nameZh: "张明",
                role: "CEO & Co-Founder",
                bio: "Former senior architect at Alibaba Cloud with 15 years of distributed systems experience",
                gradient: "from-primary to-blue-400",
              },
              {
                name: "Na Li",
                nameZh: "李娜",
                role: "CTO & Co-Founder",
                bio: "Former Google AI researcher specializing in time series data and machine learning",
                gradient: "from-purple-500 to-indigo-400",
              },
              {
                name: "Qiang Wang",
                nameZh: "王强",
                role: "VP of Engineering",
                bio: "Former principal engineer at Microsoft responsible for core platform architecture",
                gradient: "from-emerald-500 to-teal-400",
              },
            ].map((member, idx) => (
              <div
                key={idx}
                className="stagger-slide-up bg-white dark:bg-gray-800 rounded-xl text-center overflow-hidden group hover:shadow-[rgba(0,0,0,0.08)_0px_0px_0px_1px,rgba(0,0,0,0.06)_0px_4px_4px,rgba(0,0,0,0.04)_0px_8px_8px_-8px,#fafafa_0px_0px_0px_1px] transition-all duration-300"
                style={{ animationDelay: `${idx * 80}ms`, boxShadow: "rgba(0, 0, 0, 0.08) 0px 0px 0px 1px, rgba(0, 0, 0, 0.04) 0px 2px 2px, #fafafa 0px 0px 0px 1px" }}
              >
                {/* Gradient top strip */}
                <div className={`h-20 bg-gradient-to-r ${member.gradient} opacity-80`} />

                {/* Avatar overlapping gradient */}
                <div className="relative -mt-10 mb-4">
                  <div className={`w-20 h-20 mx-auto rounded-full bg-gradient-to-br ${member.gradient} flex items-center justify-center ring-4 ring-white dark:ring-gray-800 shadow-lg transition-transform duration-200 group-hover:scale-105`}>
                    <span className="text-2xl font-display font-semibold text-white">
                      {member.name[0]}
                    </span>
                  </div>
                </div>

                <div className="px-6 pb-6">
                  <h3 className="text-h4 font-display font-semibold text-gray-900 dark:text-gray-50 mb-0.5">
                    {member.name}
                  </h3>
                  <p className="text-body-sm text-gray-500 dark:text-gray-400 mb-0.5">
                    {member.nameZh}
                  </p>
                  <p className="text-body-sm text-primary font-medium mb-3">
                    {member.role}
                  </p>
                  <p className="text-body text-gray-600 dark:text-gray-400">
                    {member.bio}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="relative py-24 px-4 sm:px-6 lg:px-8 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary via-blue-600 to-blue-500" />
        <div className="absolute top-10 left-10 w-64 h-64 rounded-full bg-white/5 blur-3xl" />
        <div className="absolute bottom-10 right-20 w-48 h-48 rounded-full bg-white/5 blur-3xl" />

        <div className="relative z-10 max-w-4xl mx-auto text-center">
          <h2 className="text-h1 font-display text-white mb-6">
            Join Our Journey
          </h2>
          <p className="text-body-lg text-white/90 mb-10">
            We are looking for talented individuals to join our team
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/dashboard">
              <Button
                className="bg-white text-primary hover:bg-gray-50 border-0 shadow-lg"
                size="lg"
              >
                View Open Positions
              </Button>
            </Link>
            <Button
              variant="ghost"
              size="lg"
              className="!text-white !border-white/30 hover:!bg-white/10"
            >
              Contact Us
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 sm:px-6 lg:px-8 border-t border-gray-200 dark:border-gray-800">
        <div className="max-w-7xl mx-auto text-center">
          <p className="text-body-sm text-gray-500 dark:text-gray-400">
            &copy; 2026 IoTDB Enhanced. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
