/** Extracted from prisma/seed.ts (round-156 批3a) — data-only move, logic unchanged. */
export const FACTORIES = [
	// Australia
	{
		code: "AU-847",
		name: "Teys Wagga Wagga",
		nameLocal: "Teys Wagga Wagga",
		country: "AU",
		region: "NSW",
		capacity: 1200,
		accredited: ["CN", "US", "JP", "EU", "KR"],
	},
	{
		code: "AU-239",
		name: "JBS Beef City",
		nameLocal: "JBS Beef City",
		country: "AU",
		region: "QLD",
		capacity: 1400,
		accredited: ["CN", "US", "JP", "EU", "KR"],
	},
	{
		code: "AU-1260",
		name: "Teys Naracoorte",
		nameLocal: "Teys Naracoorte",
		country: "AU",
		region: "SA",
		capacity: 900,
		accredited: ["CN", "US", "JP", "EU"],
	},
	{
		code: "AU-514",
		name: "Australian Meat Holdings",
		nameLocal: "AMH Dinmore",
		country: "AU",
		region: "QLD",
		capacity: 1500,
		accredited: ["CN", "US", "JP", "EU"],
	},
	{
		code: "AU-235",
		name: "JBS Riverina",
		nameLocal: "JBS Riverina",
		country: "AU",
		region: "NSW",
		capacity: 1000,
		accredited: ["CN", "US", "JP", "EU"],
	},
	{
		code: "AU-93",
		name: "Thomas Foods International",
		nameLocal: "Thomas Foods",
		country: "AU",
		region: "SA",
		capacity: 800,
		accredited: ["CN", "US", "EU"],
	},
	// Brazil
	{
		code: "BR-SIF2057",
		name: "JBS Lins",
		nameLocal: "JBS Lins",
		country: "BR",
		region: "SP",
		capacity: 2000,
		accredited: ["CN", "US", "EU", "KR", "JP"],
	},
	{
		code: "BR-SIF431",
		name: "Marfrig Bataguassu",
		nameLocal: "Marfrig Bataguassu",
		country: "BR",
		region: "MS",
		capacity: 1800,
		accredited: ["CN", "US", "EU", "KR"],
	},
	{
		code: "BR-SIF2583",
		name: "Minerva Uberaba",
		nameLocal: "Minerva Uberaba",
		country: "BR",
		region: "MG",
		capacity: 1200,
		accredited: ["CN", "EU", "KR"],
	},
	{
		code: "BR-SIF2011",
		name: "JBS Barretos",
		nameLocal: "JBS Barretos",
		country: "BR",
		region: "SP",
		capacity: 2500,
		accredited: ["CN", "US", "EU", "KR", "JP"],
	},
	{
		code: "BR-SIF379",
		name: "Marfrig Várzea Grande",
		nameLocal: "Marfrig Várzea Grande",
		country: "BR",
		region: "MT",
		capacity: 1500,
		accredited: ["CN", "EU"],
	},
	// Argentina
	{
		code: "AR-1920",
		name: "Swift Rosario",
		nameLocal: "Swift Rosario",
		country: "AR",
		region: "Santa Fe",
		capacity: 1100,
		accredited: ["CN", "EU", "IL", "CL"],
	},
	{
		code: "AR-2077",
		name: "Quickfood",
		nameLocal: "Quickfood",
		country: "AR",
		region: "Buenos Aires",
		capacity: 800,
		accredited: ["CN", "EU", "US"],
	},
	{
		code: "AR-2008",
		name: "Friar San Jorge",
		nameLocal: "Friar San Jorge",
		country: "AR",
		region: "Córdoba",
		capacity: 600,
		accredited: ["CN", "EU"],
	},
	// Uruguay
	{
		code: "UY-379",
		name: "Frigorífico Rosario",
		nameLocal: "Frigorífico Rosario",
		country: "UY",
		region: "Colonia",
		capacity: 500,
		accredited: ["CN", "US", "EU", "KR"],
	},
	{
		code: "UY-310",
		name: "Frigorífico pul",
		nameLocal: "Frigorífico pul",
		country: "UY",
		region: "Canelones",
		capacity: 450,
		accredited: ["CN", "US", "EU"],
	},
	// USA
	{
		code: "US-JBS-GREELEY",
		name: "JBS USA Greeley",
		nameLocal: "JBS Greeley",
		country: "US",
		region: "CO",
		capacity: 5500,
		accredited: ["JP", "KR", "MX"],
	},
	{
		code: "US-CARGILL-DODGE",
		name: "Cargill Dodge City",
		nameLocal: "Cargill Dodge City",
		country: "US",
		region: "KS",
		capacity: 5000,
		accredited: ["JP", "KR", "MX"],
	},
	{
		code: "US-TYSON-DAKOTA",
		name: "Tyson Dakota City",
		nameLocal: "Tyson Dakota City",
		country: "US",
		region: "NE",
		capacity: 6000,
		accredited: ["JP", "KR", "MX"],
	},
	{
		code: "US-NATIONAL-DENVER",
		name: "National Beef Denver",
		nameLocal: "National Denver",
		country: "US",
		region: "CO",
		capacity: 3000,
		accredited: ["JP", "KR"],
	},
];
