/** Extracted from prisma/seed.ts (round-156 批3a) — data-only move, logic unchanged. */
export const COMMODITIES = [
	// Domestic beef cuts were removed with the domestic dimension
	// (round-155) — the platform is beef-foreign-trade only.

	// Imported beef - Australia
	{
		slug: "aus_brisket_m7",
		name: "Australian Brisket M7",
		nameCn: "澳洲牛腩 M7",
		category: "beef_cuts",
		subcategory: "brisket",
		grade: "M7",
		originCountry: "AUS",
		factoryCode: "847",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "aus_sirloin_m9",
		name: "Australian Sirloin M9",
		nameCn: "澳洲西冷 M9",
		category: "beef_cuts",
		subcategory: "sirloin",
		grade: "M9",
		originCountry: "AUS",
		factoryCode: "239",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "aus_shin_m5",
		name: "Australian Shin M5",
		nameCn: "澳洲牛腱 M5",
		category: "beef_cuts",
		subcategory: "shin",
		grade: "M5",
		originCountry: "AUS",
		factoryCode: "1260",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "aus_oyster_blade_m7",
		name: "Australian Oyster Blade M7",
		nameCn: "澳洲板腱 M7",
		category: "beef_cuts",
		subcategory: "oyster_blade",
		grade: "M7",
		originCountry: "AUS",
		factoryCode: "514",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "aus_thick_flank_m7",
		name: "Australian Thick Flank M7",
		nameCn: "澳洲牛展 M7",
		category: "beef_cuts",
		subcategory: "thick_flank",
		grade: "M7",
		originCountry: "AUS",
		factoryCode: "847",
		unit: "CNY/kg",
		currency: "CNY",
	},

	// Imported beef - Brazil
	{
		slug: "bra_brisket",
		name: "Brazilian Brisket",
		nameCn: "巴西牛腩",
		category: "beef_cuts",
		subcategory: "brisket",
		originCountry: "BRA",
		factoryCode: "SIF2057",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "bra_shin",
		name: "Brazilian Shin",
		nameCn: "巴西牛腱",
		category: "beef_cuts",
		subcategory: "shin",
		originCountry: "BRA",
		factoryCode: "SIF431",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "bra_frozen_boneless",
		name: "Brazilian Frozen Boneless Beef",
		nameCn: "巴西冷冻去骨牛肉",
		category: "beef_cuts",
		subcategory: "boneless",
		originCountry: "BRA",
		factoryCode: "SIF2583",
		unit: "CNY/kg",
		currency: "CNY",
	},

	// Imported beef - Argentina
	{
		slug: "arg_shin",
		name: "Argentine Shin",
		nameCn: "阿根廷牛腱",
		category: "beef_cuts",
		subcategory: "shin",
		originCountry: "ARG",
		factoryCode: "1920",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "arg_brisket",
		name: "Argentine Brisket",
		nameCn: "阿根廷牛腩",
		category: "beef_cuts",
		subcategory: "brisket",
		originCountry: "ARG",
		factoryCode: "2077",
		unit: "CNY/kg",
		currency: "CNY",
	},

	// Imported beef - Uruguay
	{
		slug: "ury_thick_flank",
		name: "Uruguayan Thick Flank",
		nameCn: "乌拉圭牛展",
		category: "beef_cuts",
		subcategory: "thick_flank",
		originCountry: "URY",
		factoryCode: "379",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "ury_shin",
		name: "Uruguayan Shin",
		nameCn: "乌拉圭牛腱",
		category: "beef_cuts",
		subcategory: "shin",
		originCountry: "URY",
		factoryCode: "310",
		unit: "CNY/kg",
		currency: "CNY",
	},

	// Live cattle (domestic CN live-cattle removed with the domestic
	// dimension, round-155; CME live/feeder futures remain below)

	// International futures
	{
		slug: "cme_live_cattle",
		name: "CME Live Cattle Futures",
		nameCn: "CME活牛期货",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "cme_feeder_cattle",
		name: "CME Feeder Cattle Futures",
		nameCn: "CME育肥牛期货",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},

	// Grain & Feed (domestic CN corn/soybean-meal removed with the
	// domestic dimension, round-155; global grain/futures series remain)

	// Exchange rates
	{
		slug: "usd_cny",
		name: "USD/CNY",
		nameCn: "美元/人民币",
		category: "forex",
		unit: "rate",
		currency: "CNY",
	},
	{
		slug: "aud_usd",
		name: "AUD/USD",
		nameCn: "澳元/美元",
		category: "forex",
		unit: "rate",
		currency: "USD",
	},
	{
		slug: "brl_usd",
		name: "BRL/USD",
		nameCn: "雷亚尔/美元",
		category: "forex",
		unit: "rate",
		currency: "USD",
	},

	// Additional domestic beef cuts removed with the domestic dimension
	// (round-155).

	// Additional imported beef
	{
		slug: "aus_rump_m5",
		name: "Australian Rump M5",
		nameCn: "澳洲黄瓜条 M5",
		category: "beef_cuts",
		subcategory: "rump",
		grade: "M5",
		originCountry: "AUS",
		factoryCode: "239",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "aus_cube_roll_m9",
		name: "Australian Cube Roll M9",
		nameCn: "澳洲眼肉 M9",
		category: "beef_cuts",
		subcategory: "cube_roll",
		grade: "M9",
		originCountry: "AUS",
		factoryCode: "239",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "bra_topside",
		name: "Brazilian Topside",
		nameCn: "巴西小米龙",
		category: "beef_cuts",
		subcategory: "topside",
		originCountry: "BRA",
		factoryCode: "SIF2057",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "bra_round",
		name: "Brazilian Round",
		nameCn: "巴西大黄瓜条",
		category: "beef_cuts",
		subcategory: "round",
		originCountry: "BRA",
		factoryCode: "SIF431",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "arg_forequarter",
		name: "Argentine Forequarter",
		nameCn: "阿根廷前腱",
		category: "beef_cuts",
		subcategory: "forequarter",
		originCountry: "ARG",
		factoryCode: "1920",
		unit: "CNY/kg",
		currency: "CNY",
	},
	{
		slug: "ury_boneless",
		name: "Uruguayan Boneless Beef",
		nameCn: "乌拉圭去骨牛肉",
		category: "beef_cuts",
		subcategory: "boneless",
		originCountry: "URY",
		factoryCode: "379",
		unit: "CNY/kg",
		currency: "CNY",
	},

	// Other meat
	{
		slug: "nz_lamb_leg",
		name: "NZ Lamb Leg",
		nameCn: "新西兰羊腿",
		category: "other_meat",
		subcategory: "lamb",
		originCountry: "NZ",
		unit: "CNY/kg",
		currency: "CNY",
	},

	// Additional grain & feed (domestic CN wheat/sorghum/soybean-oil
	// removed with the domestic dimension, round-155)
	{
		slug: "dalian_palm_oil",
		name: "Palm Oil (Dalian)",
		nameCn: "棕榈油（大商所）",
		category: "feed",
		originCountry: "MY",
		unit: "CNY/ton",
		currency: "CNY",
	},

	// Additional forex
	{
		slug: "eur_usd",
		name: "EUR/USD",
		nameCn: "欧元/美元",
		category: "forex",
		unit: "rate",
		currency: "USD",
	},
	{
		slug: "gbp_usd",
		name: "GBP/USD",
		nameCn: "英镑/美元",
		category: "forex",
		unit: "rate",
		currency: "USD",
	},

	// Shipping index
	{
		slug: "bdi",
		name: "Baltic Dry Index",
		nameCn: "波罗的海干散货指数",
		category: "shipping",
		unit: "index",
		currency: "USD",
	},

	// USDA AMS sourced (US livestock prices)
	{
		slug: "live_cattle_us",
		name: "US Live Cattle (5-Area)",
		nameCn: "美国活牛（五区加权）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "feeder_cattle_us",
		name: "US Feeder Cattle",
		nameCn: "美国育肥牛",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "boxed_beef_choice",
		name: "US Boxed Beef Choice Cutout",
		nameCn: "美国Choice级箱切牛肉",
		category: "beef_cuts",
		subcategory: "cutout",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "beef_cutout_us",
		name: "US Beef Cutout Composite",
		nameCn: "美国牛肉综合切割价值",
		category: "beef_cuts",
		subcategory: "cutout",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},

	// FAO Food Price Indices
	{
		slug: "fao_food_index",
		name: "FAO Food Price Index",
		nameCn: "FAO食品价格指数",
		category: "index",
		unit: "index",
		currency: "USD",
	},
	{
		slug: "fao_meat_index",
		name: "FAO Meat Price Index",
		nameCn: "FAO肉类价格指数",
		category: "index",
		unit: "index",
		currency: "USD",
	},
	{
		slug: "fao_dairy_index",
		name: "FAO Dairy Price Index",
		nameCn: "FAO乳制品价格指数",
		category: "index",
		unit: "index",
		currency: "USD",
	},
	{
		slug: "fao_cereals_index",
		name: "FAO Cereals Price Index",
		nameCn: "FAO谷物价格指数",
		category: "index",
		unit: "index",
		currency: "USD",
	},
	{
		slug: "fao_oils_index",
		name: "FAO Oils Price Index",
		nameCn: "FAO油脂价格指数",
		category: "index",
		unit: "index",
		currency: "USD",
	},

	// US grain futures
	{
		slug: "us_soybean",
		name: "US Soybean Futures",
		nameCn: "美豆期货",
		category: "futures",
		originCountry: "USA",
		unit: "US cents/bushel",
		currency: "USD",
	},

	// ── World Bank commodities (energy) ──
	{
		slug: "crude_oil_wti",
		name: "Crude Oil (WTI)",
		nameCn: "WTI原油",
		category: "energy",
		unit: "USD/bbl",
		currency: "USD",
	},
	{
		slug: "crude_oil_brent",
		name: "Crude Oil (Brent)",
		nameCn: "布伦特原油",
		category: "energy",
		unit: "USD/bbl",
		currency: "USD",
	},
	{
		slug: "natural_gas_us",
		name: "Natural Gas (US)",
		nameCn: "天然气（美国）",
		category: "energy",
		unit: "USD/MMBtu",
		currency: "USD",
	},
	{
		slug: "coal_australia",
		name: "Coal (Australia)",
		nameCn: "澳洲煤炭",
		category: "energy",
		unit: "USD/ton",
		currency: "USD",
	},

	// ── World Bank commodities (metals) ──
	{
		slug: "copper_lme",
		name: "Copper (LME)",
		nameCn: "LME铜",
		category: "metals",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "aluminum_lme",
		name: "Aluminum (LME)",
		nameCn: "LME铝",
		category: "metals",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "iron_ore_cfr",
		name: "Iron Ore (CFR China)",
		nameCn: "铁矿石（中国CFR）",
		category: "metals",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "gold_lbma",
		name: "Gold (LBMA)",
		nameCn: "黄金（LBMA）",
		category: "metals",
		unit: "USD/troy oz",
		currency: "USD",
	},
	{
		slug: "silver_lbma",
		name: "Silver (LBMA)",
		nameCn: "白银（LBMA）",
		category: "metals",
		unit: "USD/troy oz",
		currency: "USD",
	},

	// ── World Bank commodities (grains & oilseeds) ──
	{
		slug: "soybeans_cbot",
		name: "Soybeans (CBOT)",
		nameCn: "大豆（CBOT）",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "soybean_meal_cbot",
		name: "Soybean Meal (CBOT)",
		nameCn: "豆粕（CBOT）",
		category: "feed",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "soybean_oil_cbot",
		name: "Soybean Oil (CBOT)",
		nameCn: "豆油（CBOT）",
		category: "feed",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "wheat_us_srw",
		name: "Wheat (US SRW)",
		nameCn: "小麦（美国软红冬）",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "wheat_us_hrw",
		name: "Wheat (US HRW)",
		nameCn: "小麦（美国硬红冬）",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "corn_cbot",
		name: "Corn (CBOT)",
		nameCn: "玉米（CBOT）",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "rice_thai",
		name: "Rice (Thai 5%)",
		nameCn: "大米（泰国5%）",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},

	// ── World Bank commodities (soft commodities) ──
	{
		slug: "sugar_world",
		name: "Sugar (World)",
		nameCn: "糖（国际）",
		category: "soft_commodities",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "coffee_arabica",
		name: "Coffee (Arabica)",
		nameCn: "咖啡（阿拉比卡）",
		category: "soft_commodities",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "coffee_robusta",
		name: "Coffee (Robusta)",
		nameCn: "咖啡（罗布斯塔）",
		category: "soft_commodities",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "cocoa",
		name: "Cocoa",
		nameCn: "可可",
		category: "soft_commodities",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "cotton_cotlook",
		name: "Cotton (Cotlook A)",
		nameCn: "棉花（Cotlook A）",
		category: "soft_commodities",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "rubber_tsr20",
		name: "Rubber (TSR20)",
		nameCn: "橡胶（TSR20）",
		category: "soft_commodities",
		unit: "USD/kg",
		currency: "USD",
	},

	// ── World Bank commodities (meat & dairy) ──
	{
		slug: "beef_australia",
		name: "Beef (Australia)",
		nameCn: "牛肉（澳洲）",
		category: "meat_dairy",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "beef_us_choice",
		name: "Beef (US Choice)",
		nameCn: "牛肉（美国Choice）",
		category: "meat_dairy",
		unit: "USD/kg",
		currency: "USD",
	},
	{
		slug: "chicken_whole",
		name: "Chicken (Whole)",
		nameCn: "整鸡",
		category: "meat_dairy",
		unit: "USD/kg",
		currency: "USD",
	},

	// ── World Bank commodities (fertilizers) ──
	{
		slug: "urea",
		name: "Urea",
		nameCn: "尿素",
		category: "fertilizer",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "diammonium_phosphate",
		name: "DAP Fertilizer",
		nameCn: "磷酸二铵",
		category: "fertilizer",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "potassium_chloride",
		name: "Potash (MOP)",
		nameCn: "氯化钾",
		category: "fertilizer",
		unit: "USD/ton",
		currency: "USD",
	},

	// ── CME Futures (additional) ──
	{
		slug: "live_cattle_cme",
		name: "Live Cattle Futures (CME)",
		nameCn: "活牛期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "feeder_cattle_cme",
		name: "Feeder Cattle Futures (CME)",
		nameCn: "育肥牛期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "lean_hogs_cme",
		name: "Lean Hogs Futures (CME)",
		nameCn: "瘦肉猪期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/cwt",
		currency: "USD",
	},
	{
		slug: "corn_cme",
		name: "Corn Futures (CME)",
		nameCn: "玉米期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/bu",
		currency: "USD",
	},
	{
		slug: "soybeans_cme",
		name: "Soybean Futures (CME)",
		nameCn: "大豆期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/bu",
		currency: "USD",
	},
	{
		slug: "wheat_cme",
		name: "Wheat Futures (CME)",
		nameCn: "小麦期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/bu",
		currency: "USD",
	},
	{
		slug: "soybean_meal_cme",
		name: "Soybean Meal Futures (CME)",
		nameCn: "豆粕期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "soybean_oil_cme",
		name: "Soybean Oil Futures (CME)",
		nameCn: "豆油期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/lb",
		currency: "USD",
	},
	{
		slug: "crude_oil_cme",
		name: "Crude Oil Futures (CME)",
		nameCn: "原油期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/bbl",
		currency: "USD",
	},
	{
		slug: "natural_gas_cme",
		name: "Natural Gas Futures (CME)",
		nameCn: "天然气期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/MMBtu",
		currency: "USD",
	},
	{
		slug: "gold_cme",
		name: "Gold Futures (CME)",
		nameCn: "黄金期货（CME）",
		category: "futures",
		originCountry: "USA",
		unit: "USD/troy oz",
		currency: "USD",
	},
	{
		slug: "coffee_cme",
		name: "Coffee Futures (CME)",
		nameCn: "咖啡期货（CME）",
		category: "futures",
		unit: "USD/lb",
		currency: "USD",
	},
	{
		slug: "sugar11_cme",
		name: "Sugar #11 Futures (CME)",
		nameCn: "糖11号期货（CME）",
		category: "futures",
		unit: "USD/lb",
		currency: "USD",
	},
	{
		slug: "cotton2_cme",
		name: "Cotton #2 Futures (CME)",
		nameCn: "棉花2号期货（CME）",
		category: "futures",
		unit: "USD/lb",
		currency: "USD",
	},

	// ── Indices ──
	{
		slug: "commodity_price_index",
		name: "Commodity Price Index",
		nameCn: "大宗商品价格指数",
		category: "indices",
		unit: "index",
		currency: "USD",
	},

	// ── CBOT + FRED carcass (parity with the live prod catalog; these
	// slugs exist in production from scraper-era writes. The 11
	// `*_wholesale_cn` domestic wholesale series were removed with the
	// domestic dimension, round-155) ──
	{
		slug: "beef_carcass_us",
		// §十七 fix (v3.3.0 批2): seed mirrors the post-round-126 PROD
		// identity — IMF global beef monthly benchmark (PBEEFUSDM),
		// USC/lb. The old "US Beef Carcass (FRED) / USD/cwt" was the
		// pre-fix mislabel era (CBBTCUSD Bitcoin rows).
		name: "Global Beef Price (IMF via FRED)",
		nameCn: "全球牛肉价格（IMF 月度）",
		category: "beef_cuts",
		unit: "USC/lb",
		currency: "USD",
	},
	{
		slug: "corn_cbOT",
		name: "Corn (CBOT)",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},
	{
		slug: "soybeans_cbOT",
		name: "Soybeans (CBOT)",
		category: "grain",
		unit: "USD/ton",
		currency: "USD",
	},
];

export const PRICE_BASELINES: Record<string, { base: number; volatility: number }> = {
	aus_brisket_m7: { base: 42, volatility: 3 },
	aus_sirloin_m9: { base: 95, volatility: 6 },
	aus_shin_m5: { base: 38, volatility: 2 },
	aus_oyster_blade_m7: { base: 58, volatility: 4 },
	aus_thick_flank_m7: { base: 48, volatility: 3 },
	bra_brisket: { base: 32, volatility: 2 },
	bra_shin: { base: 36, volatility: 2 },
	bra_frozen_boneless: { base: 28, volatility: 2 },
	arg_shin: { base: 38, volatility: 2 },
	arg_brisket: { base: 30, volatility: 2 },
	ury_thick_flank: { base: 40, volatility: 3 },
	ury_shin: { base: 42, volatility: 3 },
	cme_live_cattle: { base: 185, volatility: 8 },
	cme_feeder_cattle: { base: 245, volatility: 12 },
	usd_cny: { base: 7.25, volatility: 0.1 },
	aud_usd: { base: 0.65, volatility: 0.015 },
	// brl_usd baseline sits at the exchange_rate_api scale (1/BRL ≈ 0.18)
	// on purpose — the authoritative-source guards assert fred's USD/BRL
	// ≈ 5.0 wins over this inverted scale (see the DEXBZUS fixture below).
	brl_usd: { base: 0.18, volatility: 0.008 },
	// CBOT + FRED carcass (slugs above; CN wholesale baselines removed
	// with the domestic dimension, round-155)
	beef_carcass_us: { base: 330, volatility: 6 },
	corn_cbOT: { base: 170, volatility: 6 },
	soybeans_cbOT: { base: 380, volatility: 12 },
	aus_rump_m5: { base: 48, volatility: 2 },
	aus_cube_roll_m9: { base: 110, volatility: 6 },
	bra_topside: { base: 28, volatility: 1.5 },
	bra_round: { base: 25, volatility: 1.2 },
	arg_forequarter: { base: 24, volatility: 1 },
	ury_boneless: { base: 30, volatility: 1.5 },
	nz_lamb_leg: { base: 65, volatility: 4 },
	dalian_palm_oil: { base: 7800, volatility: 180 },
	eur_usd: { base: 1.08, volatility: 0.008 },
	gbp_usd: { base: 1.27, volatility: 0.01 },
	bdi: { base: 1800, volatility: 60 },
	live_cattle_us: { base: 185, volatility: 8 },
	feeder_cattle_us: { base: 245, volatility: 12 },
	boxed_beef_choice: { base: 310, volatility: 10 },
	beef_cutout_us: { base: 290, volatility: 8 },
	fao_food_index: { base: 125, volatility: 3 },
	fao_meat_index: { base: 118, volatility: 4 },
	fao_dairy_index: { base: 130, volatility: 5 },
	fao_cereals_index: { base: 135, volatility: 6 },
	fao_oils_index: { base: 150, volatility: 7 },
	us_soybean: { base: 1400, volatility: 30 },

	// World Bank energy
	crude_oil_wti: { base: 72, volatility: 3 },
	crude_oil_brent: { base: 76, volatility: 3 },
	natural_gas_us: { base: 2.5, volatility: 0.2 },
	coal_australia: { base: 130, volatility: 8 },

	// World Bank metals
	copper_lme: { base: 9200, volatility: 200 },
	aluminum_lme: { base: 2350, volatility: 50 },
	iron_ore_cfr: { base: 120, volatility: 5 },
	gold_lbma: { base: 2350, volatility: 30 },
	silver_lbma: { base: 28, volatility: 0.8 },

	// World Bank grains
	soybeans_cbot: { base: 420, volatility: 15 },
	soybean_meal_cbot: { base: 380, volatility: 12 },
	soybean_oil_cbot: { base: 950, volatility: 25 },
	wheat_us_srw: { base: 240, volatility: 10 },
	wheat_us_hrw: { base: 280, volatility: 12 },
	corn_cbot: { base: 190, volatility: 8 },
	rice_thai: { base: 560, volatility: 20 },

	// World Bank soft commodities
	sugar_world: { base: 0.28, volatility: 0.02 },
	coffee_arabica: { base: 4.5, volatility: 0.3 },
	coffee_robusta: { base: 3.2, volatility: 0.2 },
	cocoa: { base: 8.5, volatility: 0.5 },
	cotton_cotlook: { base: 1.9, volatility: 0.08 },
	rubber_tsr20: { base: 1.6, volatility: 0.06 },

	// World Bank meat & dairy
	beef_australia: { base: 5.8, volatility: 0.2 },
	beef_us_choice: { base: 6.2, volatility: 0.25 },
	chicken_whole: { base: 2.5, volatility: 0.1 },

	// World Bank fertilizers
	urea: { base: 350, volatility: 15 },
	diammonium_phosphate: { base: 580, volatility: 20 },
	potassium_chloride: { base: 320, volatility: 12 },

	// CME futures
	live_cattle_cme: { base: 188, volatility: 5 },
	feeder_cattle_cme: { base: 255, volatility: 8 },
	lean_hogs_cme: { base: 82, volatility: 3 },
	corn_cme: { base: 4.5, volatility: 0.15 },
	soybeans_cme: { base: 12.5, volatility: 0.3 },
	wheat_cme: { base: 5.8, volatility: 0.2 },
	soybean_meal_cme: { base: 340, volatility: 10 },
	soybean_oil_cme: { base: 0.52, volatility: 0.02 },
	crude_oil_cme: { base: 72, volatility: 2 },
	natural_gas_cme: { base: 2.4, volatility: 0.15 },
	gold_cme: { base: 2350, volatility: 25 },
	coffee_cme: { base: 1.85, volatility: 0.08 },
	sugar11_cme: { base: 0.22, volatility: 0.01 },
	cotton2_cme: { base: 0.72, volatility: 0.03 },

	// Indices
	commodity_price_index: { base: 180, volatility: 4 },
};

export const DECLARED_SOURCES: Record<string, string> = {
	corn_cme: "usda_ams",
	natural_gas_cme: "fred",
	aluminum_lme: "fred",
	coffee_arabica: "fred",
	copper_lme: "fred",
	crude_oil_wti: "fred",
	iron_ore_cfr: "fred",
	natural_gas_us: "fred",
	rice_thai: "fred",
	rubber_tsr20: "fred",
	soybeans_cbot: "fred",
	sugar_world: "fred",
	wheat_us_srw: "fred",
	aud_usd: "fred",
	usd_cny: "fred",
	crude_oil_cme: "fred",
	live_cattle_cme: "cme",
};

export const MULTI_SOURCE_SLUGS = [
	"aus_sirloin_m9",
	"aus_cube_roll_m9",
	"corn_cbot",
	"soybeans_cbot",
	"wheat_us_srw",
	"sugar_world",
	"coffee_arabica",
	"cotton_cotlook",
	"crude_oil_brent",
	"live_cattle_cme",
	"crude_oil_wti",
	"gold_lbma",
	"copper_lme",
	"beef_australia",
	"corn_cme",
];
