apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trademind.fullname" . }}-secrets
  labels:
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password | default "changeme" }}@{{ .Release.Name }}-postgresql-primary:5432/{{ .Values.postgresql.auth.database }}?schema=public"
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default (randAlphaNum 32) | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | default (randAlphaNum 32) | quote }}
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6379"
