/**
 * Beef monthly backtest evidence panel (IMPROVEMENT-PLAN v3.1.0 批1).
 *
 * A static, DATED snapshot of the rolling-origin backtest report
 * (docs/backtests/beef-monthly-2026-08.md, generated by
 * backend/scripts/backtest-monthly-series.ts — chronos calls are
 * payload-seeded and sequential, so re-runs are bit-identical). Shown on
 * the public /ai/track-record page: these numbers are experimental
 * EVIDENCE, not live metrics, and are labeled with their run date and
 * reproducibility path. Update this constant only by re-running the script
 * and copying the fresh table.
 */

export interface BeefBacktestRow {
	modelId: string;
	/** Median MAPE over 36 rolling origins, H=1 month (H=3 in the next field). */
	medianMapeH1: number;
	medianMapeH3: number;
	/** Direction hit rate at H=1 (share of origins where the predicted
	 * up/down sign matched the actual, relative to the anchor point). Null
	 * for naive — a flat forecast has no direction. */
	directionH1: number | null;
	/** Share of H=1 steps inside the engine-native [lower, upper] band at
	 * the 90% level (uncalibrated baseline). */
	coverageH1: number;
}

export const BEEF_BACKTEST = {
	slug: "beef_carcass_us",
	seriesLabel: "US Beef Carcass (IMF PBEEFUSDM, monthly)",
	runDate: "2026-08-30",
	points: 195,
	origins: 36,
	sourceNote:
		"docs/backtests/beef-monthly-2026-08.md · backend/scripts/backtest-monthly-series.ts (seed-fixed, re-runs bit-identical)",
	rows: [
		{
			modelId: "arima",
			medianMapeH1: 1.46,
			medianMapeH3: 2.64,
			directionH1: 61.1,
			coverageH1: 91.7,
		},
		{
			modelId: "holtwinters",
			medianMapeH1: 1.57,
			medianMapeH3: 2.66,
			directionH1: 52.8,
			coverageH1: 91.7,
		},
		{
			modelId: "chronos_tiny",
			medianMapeH1: 1.61,
			medianMapeH3: 3.28,
			directionH1: 61.1,
			coverageH1: 72.2,
		},
		{
			modelId: "exponential_smoothing",
			medianMapeH1: 1.69,
			medianMapeH3: 2.71,
			directionH1: 38.9,
			coverageH1: 94.4,
		},
		{
			modelId: "naive_forecaster",
			medianMapeH1: 1.69,
			medianMapeH3: 2.71,
			directionH1: null,
			coverageH1: 94.4,
		},
		{
			modelId: "chronos_base",
			medianMapeH1: 1.71,
			medianMapeH3: 3.91,
			directionH1: 69.4,
			coverageH1: 77.8,
		},
		{
			modelId: "chronos_mini",
			medianMapeH1: 2.08,
			medianMapeH3: 3.62,
			directionH1: 63.9,
			coverageH1: 58.3,
		},
	] as BeefBacktestRow[],
} as const;

export default function BeefBacktestSection() {
	return (
		<section className="mt-10">
			<h2 className="mb-1 text-lg font-semibold text-foreground">
				Beef monthly backtest — rolling-origin evidence
			</h2>
			<p className="mb-3 text-xs text-muted-foreground">
				{BEEF_BACKTEST.seriesLabel} · {BEEF_BACKTEST.points} points (2010-05 → 2026-07) ·{" "}
				{BEEF_BACKTEST.origins} expanding-window origins · run {BEEF_BACKTEST.runDate}. Median MAPE
				over 7-model pool; direction = predicted vs actual up/down sign at 1 month. Live rolling
				verification of production forecasts starts maturing 2026-09.
			</p>
			<div className="overflow-x-auto rounded-lg ring-1 ring-black/5 dark:ring-white/10">
				<table className="w-full text-sm">
					<thead className="bg-muted/50 text-left text-xs uppercase tracking-wider text-muted-foreground">
						<tr>
							<th className="px-4 py-3">Model</th>
							<th className="px-4 py-3">Median MAPE · 1 mo</th>
							<th className="px-4 py-3">Median MAPE · 3 mo</th>
							<th className="px-4 py-3">Direction hit · 1 mo</th>
							<th className="px-4 py-3">Coverage · 1 mo</th>
						</tr>
					</thead>
					<tbody>
						{BEEF_BACKTEST.rows.map((row) => (
							<tr key={row.modelId} className="border-t border-black/5 dark:border-white/5">
								<td className="px-4 py-2.5 font-mono text-xs">{row.modelId}</td>
								<td className="px-4 py-2.5 tabular-nums">{row.medianMapeH1.toFixed(2)}%</td>
								<td className="px-4 py-2.5 tabular-nums text-muted-foreground">
									{row.medianMapeH3.toFixed(2)}%
								</td>
								<td className="px-4 py-2.5 tabular-nums">
									{row.directionH1 == null ? "— (flat)" : `${row.directionH1.toFixed(1)}%`}
								</td>
								<td className="px-4 py-2.5 tabular-nums text-muted-foreground">
									{row.coverageH1.toFixed(1)}%
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</div>
			<p className="mt-2 text-xs text-muted-foreground">
				Reading: every model sits within ~15% of the naive baseline at 1 month — a monthly macro
				series is near its predictability ceiling, which is exactly why we publish direction,
				calibrated intervals, and checkable verification instead of claiming a bigger model wins.
				Champion at both horizons: arima; chronos degrades at 3 months and its native intervals
				undercover (58–78% vs the nominal 90%) — production intervals are conformal-calibrated on
				verified residuals. Source: {BEEF_BACKTEST.sourceNote}.
			</p>
		</section>
	);
}
